var grammar = tracery.createGrammar({
    "origin": ["#oneWord#", "#twoWords#", "#twoWords#"],

    "oneWord":  "#onlyWord#",
    "onlyWord": "#affixedWord#",

    "twoWords":     "#firstWord# #secondWord#",
    "firstWord":    ["#modifier#", "#maybeAffixedWord#"],
    "secondWord":   "#maybeAffixedWord#",

    "affixedWord":      ["#prefixedWord#", "#prefixedWord#", "#prefixedWord#", "#prefixedWord#", "#prefixedWord#", "#suffixedWord#"],
    "maybeAffixedWord": ["#genre#", "#affixedWord#", "#affixedWord#"],
    "prefixedWord":     "#prefix##genre#",
    "suffixedWord":     "#suffixablePart##suffix#",
    "suffixablePart":   ["#genre#", "#genre#", "#genre#", "#prefix##genre#", "#modifier#", "#prefix#"],

    "genre": [
        "biker",
        "butch",
        "clown",
        "cosplay",
        "cowboy",
        "disco",
        "dragon",
        "emo",
        "fairy",
        "farmer",
        "folk",
        "funk",
        "furry",
        "gamer",
        "#geek#",
        "glitch",
        "goth",
        "grunge",
        "hacker",
        "hip hop",
        "hippie",
        "hipster",
        "jock",
        "larper",
        "librarian",
        "metal",
        "monster",
        "noir",
        "pirate",
        "prep",
        "#princex#",
        "punk",
        "skater",
        "trucker",
        "twink",
        "witch",
        "#rareGenre#",
    ],
    "rareGenre": [
        "brutalist",
        "classical",
        "modernist",
        "realist",
        "surrealist",
    ],
    "geek": [
        "geek",
        "nerd",
        "otaku",
    ],
    "princex": [
        "princex",
        "princess",
        "prince",
    ],

    "modifier": [
        "8-bit",
        "abstract",
        "art",
        "ballroom",
        "beach",
        "bespoke",
        "bubblegum",
        "business",
        "candy",
        "carnival",
        "crypt",
        "dark",
        "death",
        "deep",
        "disaster",
        "Disney",
        "fantasy",
        "forest",
        "future",
        "glam",
        "hard",
        "health",
        "horror",
        "industrial",
        "Instagram",
        "lesbian",
        "magic",
        "math",
        "medical",
        "minimal",
        "myth",
        "nature",
        "neon",
        "Neopet",
        "Nintendo",
        "nu",
        "operatic",
        "pajama",
        "pasta",
        "pastel",
        "postapocalypse",
        "power",
        "psychedelic",
        "rainbow",
        "sci-fi",
        "soft",
        "spicy",
        "swamp",
        "symphonic",
        "#geographicModifier#",
    ],
    "geographicModifier": [
        "Celtic",
        "French",
        "Latin",
        "New England",
        "Scandinavian",
        "Southern",
        "Texas",
    ],

    "prefix": [
        "acid",
        "astro",
        "bio",
        "care",
        "chill",
        "crypto",
        "cyber",
        "e-",
        "electro",
        "endo",
        "enviro",
        "fem",
        "fuck",
        "fur",
        "glow",
        "gore",
        "holo",
        "infra",
        "jump",
        "litho",
        "macro",
        "mecha",
        "mer",
        "meta",
        "mono",
        "nano",
        "neo",
        "night",
        "norm",
        "post",
        "pre",
        "proto",
        "pseudo",
        "retro",
        "sea",
        "steam",
        "synth",
        "techno",
        "trans",
        "vapor",
        "#geographicPrefix#",
    ],
    "geographicPrefix": [
        "Afro",
        "Brit",
        "euro",
        "J-",
        "K-",
    ],

    "suffix": [
        "beat",
        "core",
        "fuck",
        "pop",
        "punk",
        "style",
        "wave",
    ]
})
